name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests (verbose)
        run: |
          # Run tests with verbose output and capture logs (PowerShell on windows runners)
          flutter test --no-pub -v *> flutter_test.log
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flutter-test-log
          path: flutter_test.log
