name: Flutter unit tests

on:
  push:
    branches: [ pr/finalize-dicoding, Flutter-Fundamental-V.1 ]
  pull_request:
    branches: [ Flutter-Pemula ]

jobs:
  test:
    name: Run Flutter tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Pin a known stable Flutter SDK version to avoid runner/channel resolution
          # issues on some hosted images. Update this value if you need a newer SDK.
          # Pin a Flutter SDK that is available on the hosted runners. We
          # previously validated that '3.10.5' is downloadable on the runner
          # image. With the relaxed pubspec Dart constraint, this should
          # allow `flutter pub get` to succeed during CI.
          flutter-version: '3.10.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --reporter=expanded
