name: Flutter unit tests

on:
  push:
    branches: [ pr/finalize-dicoding, Flutter-Fundamental-V.1 ]
  pull_request:
    branches: [ Flutter-Pemula ]

jobs:
  test:
    name: Run Flutter tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # For pull_request events prefer the head ref so CI runs against
          # the branch under test instead of the merged commit (which may
          # include incompatible deps from the base branch).
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Pin a recent Flutter stable that bundles a newer Dart SDK so
          # native plugins (workmanager, flutter_local_notifications) can
          # be resolved and the code compiled. If this exact tag isn't
          # available on the hosted runner, the workflow run will fail and
          # I'll iterate to a nearby 4.x patch.
          flutter-version: '4.0.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --reporter=expanded
